# CMake generated Testfile for 
# Source directory: /home/kishan/rl_ws/src/bwi_common/stop_base/tests
# Build directory: /home/kishan/rl_ws/src/bwi_common/stop_base/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_stop_base_nosetests_test_transitions.py "/home/kishan/rl_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kishan/rl_ws/src/test_results/stop_base/nosetests-test_transitions.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/kishan/rl_ws/src/test_results/stop_base" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/kishan/rl_ws/src/bwi_common/stop_base/tests/test_transitions.py --with-xunit --xunit-file=/home/kishan/rl_ws/src/test_results/stop_base/nosetests-test_transitions.py.xml")
add_test(_ctest_stop_base_rostest_tests_stop_base_passthru.test "/home/kishan/rl_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kishan/rl_ws/src/test_results/stop_base/rostest-tests_stop_base_passthru.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kishan/rl_ws/src/bwi_common/stop_base --package=stop_base --results-filename tests_stop_base_passthru.xml --results-base-dir \"/home/kishan/rl_ws/src/test_results\" /home/kishan/rl_ws/src/bwi_common/stop_base/tests/stop_base_passthru.test ")
add_test(_ctest_stop_base_rostest_tests_stop_base_requests.test "/home/kishan/rl_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kishan/rl_ws/src/test_results/stop_base/rostest-tests_stop_base_requests.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kishan/rl_ws/src/bwi_common/stop_base --package=stop_base --results-filename tests_stop_base_requests.xml --results-base-dir \"/home/kishan/rl_ws/src/test_results\" /home/kishan/rl_ws/src/bwi_common/stop_base/tests/stop_base_requests.test ")
